### ISSUE TITLE
Server-side?

### ISSUE THREAD

**Issue by peter-mouland** [vladimirponomarev/getting-started-with-react#6]
Thanks for the tutorial, but have you attempted to implement this within a server-side rendering react app?  because `localStorage` doesn't exist on the server we hit problems.

basically, (as i'm using React-Router-v4) my step step is to only call `Auth.isUserAuthenticated()` on `componentDidMount`.  Once I get this working I will spend more time thinking about how to get this done properly. 

Have you put any thought to SSR already?

**Comment by barinbritva** [comment]
@peter-mouland, for server you need to define localStorage variable. You can use any library, for example [node-localstorage](https://github.com/lmaccherone/node-localstorage), or write small stub implementation.
